repos:
#  - repo: https://github.com/golangci/golangci-lint
#    rev: v1.59.1  # <--- nên dùng phiên bản cụ thể
#    hooks:
#      - id: golangci-lint
#        args: [--timeout=5m]

  - repo: local
    hooks:
      - id: go-oif
        name: go-oif
        entry: go-oif ./...
        language: system
        types: [ go ]
        pass_filenames: false
