// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitApp(isDebugMode bool, db string, log *zap.SugaredLogger) (*Handler, func(), error) {
	handler := NewApiBiz(log)
	return handler, func() {
	}, nil
}
