// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package serve

import (
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitServeApp(log *zap.SugaredLogger) (*JsonServer, error) {
	jsonServer := NewJsonServer(log)
	return jsonServer, nil
}
